base_url = "https://www.karlserv.eu"

title = "KarlServ"
description = "Just another random developer"
default_language = "en"

theme = "anemone"

build_search_index = false

[markdown]
highlight_code = true

[extra]
header_nav = [
  { url = "/", name_en = "/home/"},
]
twitter_card = false
default_theme = "light"
