# The URL the site will be built for
base_url = "https://karlserv.eu"

title = "KarlServ"
description = "Just another random developer"
default_language = "en"

theme = "anemone"

build_search_index = false

[markdown]
highlight_code = true

[extra]
# Put all your custom variables here

header_nav = [
  { url = "/", name_en = "/home/"},
]
twitter_card = false
default_theme = "light"
